INSERT INTO Player (name, ELO, numberPlayed) VALUES ('Joseph', 1500, 0)

INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Credicor', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Ecoline', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Helion', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Interplanetary Cinematics', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Inventrix', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Mining Guild', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Phobolog', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Tharsis Republic', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Thorgate', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('UMNI', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Saturn Systems', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Teractor', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Aphrodite', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Celestic', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Manutech', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Morning Star Inc.', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Viron', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Cheung Shing Mars', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Point Luna', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Robinson Industries', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Valley Trust', 1 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Vitor', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Aridor', 0 ,1)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Arklight', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Polyphemos', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Posdeidon', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Stormcraft Incorporated', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Arcadian Communities', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Recyclon', 0 ,0)
INSERT INTO Corporation (name, extraPreludes, extraColonies) VALUES ('Splice', 0 ,0)

INSERT INTO Prelude (name) VALUES ('Allied Bank')
INSERT INTO Prelude (name) VALUES ('Acquired Space Agency')
INSERT INTO Prelude (name) VALUES ('Aquifer Turbines')
INSERT INTO Prelude (name) VALUES ('Biofuels')
INSERT INTO Prelude (name) VALUES ('Biolab')
INSERT INTO Prelude (name) VALUES ('Biosphere Support')
INSERT INTO Prelude (name) VALUES ('Business Empire')
INSERT INTO Prelude (name) VALUES ('Dome Farming')
INSERT INTO Prelude (name) VALUES ('Donation')
INSERT INTO Prelude (name) VALUES ('Early Settlement')
INSERT INTO Prelude (name) VALUES ('Ecology Experts')
INSERT INTO Prelude (name) VALUES ('Eccentric Sponsor')
INSERT INTO Prelude (name) VALUES ('Experimental Forest')
INSERT INTO Prelude (name) VALUES ('Galilean Mining')
INSERT INTO Prelude (name) VALUES ('Great Aquifer')
INSERT INTO Prelude (name) VALUES ('Huge Asteroid')
INSERT INTO Prelude (name) VALUES ('Io Research Outpost')
INSERT INTO Prelude (name) VALUES ('Loan')
INSERT INTO Prelude (name) VALUES ('Martian Industries')
INSERT INTO Prelude (name) VALUES ('Metal-Rich Asteroid')
INSERT INTO Prelude (name) VALUES ('Metals Company')
INSERT INTO Prelude (name) VALUES ('Mining Operations')
INSERT INTO Prelude (name) VALUES ('Mohole')
INSERT INTO Prelude (name) VALUES ('Mohole Excavation')
INSERT INTO Prelude (name) VALUES ('Nitrogen Shipment')
INSERT INTO Prelude (name) VALUES ('Orbital Construction Yard')
INSERT INTO Prelude (name) VALUES ('Polar Industries')
INSERT INTO Prelude (name) VALUES ('Power Generation')
INSERT INTO Prelude (name) VALUES ('Research Network')
INSERT INTO Prelude (name) VALUES ('Self-Sufficient Colony')
INSERT INTO Prelude (name) VALUES ('Smelting Plant')
INSERT INTO Prelude (name) VALUES ('Society Support')
INSERT INTO Prelude (name) VALUES ('Supplier')
INSERT INTO Prelude (name) VALUES ('Supply Drop')
INSERT INTO Prelude (name) VALUES ('UMNI Contractor')

INSERT INTO Colony (name) VALUES ('Callisto')
INSERT INTO Colony (name) VALUES ('Ceres')
INSERT INTO Colony (name) VALUES ('Enceladus')
INSERT INTO Colony (name) VALUES ('Europa')
INSERT INTO Colony (name) VALUES ('Ganymede')
INSERT INTO Colony (name) VALUES ('Io')
INSERT INTO Colony (name) VALUES ('Luna')
INSERT INTO Colony (name) VALUES ('Miranda')
INSERT INTO Colony (name) VALUES ('Pluto')
INSERT INTO Colony (name) VALUES ('Titan')
INSERT INTO Colony (name) VALUES ('Triton')

INSERT INTO Awards (type, name) VALUES ('Milestone', 'Terraformer')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Mayor')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Gardener')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Builder')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Planner')
INSERT INTO Awards (type, name) VALUES ('Award', 'Landlord')
INSERT INTO Awards (type, name) VALUES ('Award', 'Banker')
INSERT INTO Awards (type, name) VALUES ('Award', 'Scientist')
INSERT INTO Awards (type, name) VALUES ('Award', 'Thermalist')
INSERT INTO Awards (type, name) VALUES ('Award', 'Miner')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Diversifier')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Tactician')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Polar Explorer')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Energiser')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Rim Settler')
INSERT INTO Awards (type, name) VALUES ('Award', 'Cultivator')
INSERT INTO Awards (type, name) VALUES ('Award', 'Magnate')
INSERT INTO Awards (type, name) VALUES ('Award', 'Space Baron')
INSERT INTO Awards (type, name) VALUES ('Award', 'Eccentric')
INSERT INTO Awards (type, name) VALUES ('Award', 'Contractor')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Generalist')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Specialist')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Ecologist')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Tycoon')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Legend')
INSERT INTO Awards (type, name) VALUES ('Award', 'Celebrity')
INSERT INTO Awards (type, name) VALUES ('Award', 'Industrialist')
INSERT INTO Awards (type, name) VALUES ('Award', 'Desert Settler')
INSERT INTO Awards (type, name) VALUES ('Award', 'Estate Dealer')
INSERT INTO Awards (type, name) VALUES ('Award', 'Benefactor')
INSERT INTO Awards (type, name) VALUES ('Milestone', 'Hoverlord')
INSERT INTO Awards (type, name) VALUES ('Award', 'Venuphile')